# Generated by Django 5.0.10 on 2025-02-05 07:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="annual_drill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "drill_name",
                    models.CharField(max_length=255, verbose_name="Drill Name"),
                ),
                (
                    "drilling_month",
                    models.CharField(max_length=50, verbose_name="Dril Month"),
                ),
            ],
            options={
                "verbose_name": "Drill Training",
                "verbose_name_plural": "Drill Trainings",
            },
        ),
        migrations.CreateModel(
            name="annual_training",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "train_name",
                    models.CharField(max_length=255, verbose_name="Training Name"),
                ),
                (
                    "training_month",
                    models.CharField(max_length=50, verbose_name="Training Month"),
                ),
            ],
            options={
                "verbose_name": "HSE Training",
                "verbose_name_plural": "HSE Trainings",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "cid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Company ID"
                    ),
                ),
                (
                    "cabb",
                    models.CharField(
                        max_length=10, verbose_name="Company Name abbreviation "
                    ),
                ),
                (
                    "cname",
                    models.CharField(max_length=255, verbose_name="Company Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "LID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Location ID"
                    ),
                ),
                (
                    "Lname",
                    models.CharField(max_length=255, verbose_name="Location Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="tool_box_meeting_topics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "meeting_topic",
                    models.CharField(
                        max_length=255, verbose_name="Tool Box Meeting Topic"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Box Meeting",
                "verbose_name_plural": "Tool Box Meetings",
            },
        ),
        migrations.CreateModel(
            name="VehicleMaker",
            fields=[
                (
                    "VMid",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Vehicle Maker ID",
                    ),
                ),
                (
                    "VMNAME",
                    models.CharField(max_length=255, verbose_name="Vehicle Maker Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Vehicle Makers",
            },
        ),
        migrations.CreateModel(
            name="VehicleOwner",
            fields=[
                (
                    "VO_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Vehicle Owner ID",
                    ),
                ),
                (
                    "VO_name",
                    models.CharField(max_length=255, verbose_name="Vehicle Owner Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Vehicle Owners",
            },
        ),
        migrations.CreateModel(
            name="Violations",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "violation_type",
                    models.CharField(max_length=255, verbose_name="Violation Type"),
                ),
            ],
            options={
                "verbose_name": "Violation",
                "verbose_name_plural": "Violations",
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "D_ID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Driver ID"
                    ),
                ),
                (
                    "D_Number",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Driver Number"
                    ),
                ),
                (
                    "D_Image",
                    models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="driver_images/",
                    ),
                ),
                (
                    "D_Name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Driver Name"
                    ),
                ),
                (
                    "Father_Name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Father Name"
                    ),
                ),
                ("CNIC", models.CharField(max_length=13, null=True)),
                (
                    "CNIC_Validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="CNIC Validity Date"
                    ),
                ),
                (
                    "Cell_Phone_Num",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Cell Phone Number"
                    ),
                ),
                (
                    "DOB",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "DL_Status",
                    models.CharField(
                        choices=[("HTV", "HTV"), ("PSV", "PSV"), ("LTV", "LTV")],
                        max_length=3,
                        null=True,
                        verbose_name="Driving License Status",
                    ),
                ),
                (
                    "Motorway_Trained",
                    models.CharField(
                        max_length=14, null=True, verbose_name="Motorway Trained"
                    ),
                ),
                (
                    "DDC_Issue_Date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Motorway Certification Issue Date",
                    ),
                ),
                ("Address", models.TextField(null=True, verbose_name="Address")),
                (
                    "License_No",
                    models.CharField(
                        max_length=20, null=True, verbose_name="License Number"
                    ),
                ),
                (
                    "HTV_License_Issue_Date",
                    models.DateField(
                        blank=True, null=True, verbose_name="HTV License Issue Date"
                    ),
                ),
                (
                    "HTV_License_Expiry_Date",
                    models.DateField(
                        blank=True, null=True, verbose_name="HTV License Expiry Date"
                    ),
                ),
                (
                    "DDC_Expiry_Date",
                    models.DateField(blank=True, null=True, verbose_name="DDC Date"),
                ),
                (
                    "Education",
                    models.CharField(
                        max_length=16, null=True, verbose_name="Education"
                    ),
                ),
                (
                    "Medical",
                    models.BooleanField(null=True, verbose_name="Medical Status"),
                ),
                (
                    "Report_Date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Medical Report Date"
                    ),
                ),
                (
                    "Lab_Name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Lab Name"
                    ),
                ),
                (
                    "Expiry_Date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Medical Expiry Date"
                    ),
                ),
                (
                    "Blood_Group",
                    models.CharField(max_length=10, verbose_name="Blood Group"),
                ),
                (
                    "Medical_Health",
                    models.CharField(
                        max_length=5, null=True, verbose_name="Medical Health"
                    ),
                ),
                (
                    "Joining_Date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Joining Date"
                    ),
                ),
                (
                    "Salary_Increment_Date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Salary Increment Date"
                    ),
                ),
                (
                    "Experience",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Experience (years)",
                    ),
                ),
                (
                    "Leave_Date",
                    models.DateField(blank=True, null=True, verbose_name="Leave Date"),
                ),
                (
                    "Leave_Resume",
                    models.DateField(
                        blank=True, null=True, verbose_name="Leave Resume Date"
                    ),
                ),
                (
                    "Driving_Age",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Driving Age (years)",
                    ),
                ),
                (
                    "Previous_Company",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Previous Company",
                    ),
                ),
                (
                    "Tank_Lorry",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Tank Lorry"
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "Oil_Marketing_Company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.company",
                        verbose_name="Oil Marketing Company",
                    ),
                ),
                (
                    "HTV_License_Authority",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.location",
                        verbose_name="HTV License Authority",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Drivers",
            },
        ),
        migrations.CreateModel(
            name="annual_training_driver",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "train1_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN1 Completed Date"
                    ),
                ),
                (
                    "train2_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN2 Completed Date"
                    ),
                ),
                (
                    "train3_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN3 Completed Date"
                    ),
                ),
                (
                    "train4_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN4 Completed Date"
                    ),
                ),
                (
                    "train5_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN5 Completed Date"
                    ),
                ),
                (
                    "train6_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN6 Completed Date"
                    ),
                ),
                (
                    "train7_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN7 Completed Date"
                    ),
                ),
                (
                    "train8_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN8 Completed Date"
                    ),
                ),
                (
                    "train9_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN9 Completed Date"
                    ),
                ),
                (
                    "train10_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN10 Completed Date"
                    ),
                ),
                (
                    "train11_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN11 Completed Date"
                    ),
                ),
                (
                    "train12_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN12 Completed Date"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.driver",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "HSE Training Driver",
                "verbose_name_plural": "HSE Training Drivers",
            },
        ),
        migrations.CreateModel(
            name="annual_drill_driver",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("train1_completed_date", models.DateField(blank=True, null=True)),
                ("train2_completed_date", models.DateField(blank=True, null=True)),
                ("train3_completed_date", models.DateField(blank=True, null=True)),
                ("train4_completed_date", models.DateField(blank=True, null=True)),
                ("train5_completed_date", models.DateField(blank=True, null=True)),
                ("train6_completed_date", models.DateField(blank=True, null=True)),
                ("train7_completed_date", models.DateField(blank=True, null=True)),
                ("train8_completed_date", models.DateField(blank=True, null=True)),
                ("train9_completed_date", models.DateField(blank=True, null=True)),
                ("train10_completed_date", models.DateField(blank=True, null=True)),
                ("train11_completed_date", models.DateField(blank=True, null=True)),
                ("train12_completed_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.driver",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dril Driver",
                "verbose_name_plural": "Drill Drivers",
            },
        ),
        migrations.CreateModel(
            name="driver_tool_box_meeting_attended",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("no_of_times_meeting_attended", models.IntegerField()),
                (
                    "meeting_attended_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.driver",
                    ),
                ),
                (
                    "meetings_attended",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.tool_box_meeting_topics",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        max_length=500, null=True, upload_to="user_images/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("TL_Number", models.CharField(max_length=255, null=True)),
                ("Capacity", models.IntegerField(null=True)),
                ("Chambers", models.CharField(max_length=255, null=True)),
                ("Model", models.IntegerField(null=True)),
                ("Engine_Number", models.CharField(max_length=255, null=True)),
                ("Chassis_Number", models.CharField(max_length=255, null=True)),
                ("Status", models.CharField(max_length=255, null=True)),
                ("Type", models.CharField(max_length=255, null=True)),
                ("Trailer_ID", models.CharField(max_length=255, null=True)),
                ("Brand", models.CharField(max_length=255, null=True)),
                (
                    "NHA_Configuration_Class",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "Gross_Empty_Trailer_Weight",
                    models.CharField(max_length=255, null=True),
                ),
                ("DIP_CHART_Date", models.DateField(null=True)),
                ("INSURANCE_Date", models.DateField(null=True)),
                ("TAX_PAID_Date", models.DateField(null=True)),
                ("FITNISSE_Date", models.DateField(null=True)),
                ("Q_FOM_Date", models.DateField(null=True)),
                ("Route_Permit_Date", models.DateField(null=True)),
                (
                    "OMC",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.company",
                    ),
                ),
                (
                    "Make",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.vehiclemaker",
                    ),
                ),
                (
                    "LEASE_BANK",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Vehicle_Owner_Bank",
                        to="dashboard.vehicleowner",
                    ),
                ),
                (
                    "LEASE_COMPANY",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Vehicle_Owner_Lease",
                        to="dashboard.vehicleowner",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vehicles",
            },
        ),
        migrations.CreateModel(
            name="Driver_Violation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "violation_date",
                    models.DateField(null=True, verbose_name="Violation Date"),
                ),
                ("violation_notes", models.TextField(null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.driver",
                        verbose_name="Driver",
                    ),
                ),
                (
                    "violation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.violations",
                        verbose_name="Violation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Violation",
                "verbose_name_plural": "Driver Violations",
            },
        ),
    ]
