# Generated by Django 4.2.6 on 2023-10-26 14:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="annual_training",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "train_name",
                    models.CharField(max_length=255, verbose_name="Training Name"),
                ),
                (
                    "training_month",
                    models.CharField(max_length=50, verbose_name="Training Month"),
                ),
            ],
            options={
                "verbose_name": "HSE Training",
                "verbose_name_plural": "HSE Trainings",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "cid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Company ID"
                    ),
                ),
                (
                    "cabb",
                    models.CharField(
                        max_length=10, verbose_name="Company Name abbreviation "
                    ),
                ),
                (
                    "cname",
                    models.CharField(max_length=255, verbose_name="Company Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "D_ID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Driver ID"
                    ),
                ),
                (
                    "D_Number",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Driver Number"
                    ),
                ),
                (
                    "D_Image",
                    models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="driver_images/",
                    ),
                ),
                (
                    "D_Name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Driver Name"
                    ),
                ),
                (
                    "Father_Name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Father Name"
                    ),
                ),
                ("CNIC", models.CharField(max_length=13, null=True, unique=True)),
                (
                    "CNIC_Validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="CNIC Validity Date"
                    ),
                ),
                (
                    "Cell_Phone_Num",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Cell Phone Number"
                    ),
                ),
                (
                    "DOB",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "DL_Status",
                    models.CharField(
                        choices=[("HTV", "HTV"), ("PSV", "PSV"), ("LTV", "LTV")],
                        max_length=3,
                        null=True,
                        verbose_name="Driving License Status",
                    ),
                ),
                (
                    "Motorway_Trained",
                    models.CharField(
                        max_length=14, null=True, verbose_name="Motorway Trained"
                    ),
                ),
                (
                    "Motorway_Cissue_Date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Motorway Certification Issue Date",
                    ),
                ),
                ("Address", models.TextField(null=True, verbose_name="Address")),
                (
                    "License_No",
                    models.CharField(
                        max_length=20, null=True, verbose_name="License Number"
                    ),
                ),
                (
                    "HTV_License_Issue_Date",
                    models.DateField(
                        blank=True, null=True, verbose_name="HTV License Issue Date"
                    ),
                ),
                (
                    "HTV_License_Expiry_Date",
                    models.DateField(
                        blank=True, null=True, verbose_name="HTV License Expiry Date"
                    ),
                ),
                (
                    "DDC_Date",
                    models.DateField(blank=True, null=True, verbose_name="DDC Date"),
                ),
                (
                    "Education",
                    models.CharField(
                        max_length=16, null=True, verbose_name="Education"
                    ),
                ),
                (
                    "Medical",
                    models.BooleanField(null=True, verbose_name="Medical Status"),
                ),
                (
                    "Report_Date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Medical Report Date"
                    ),
                ),
                (
                    "Lab_Name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Lab Name"
                    ),
                ),
                (
                    "Expiry_Date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Medical Expiry Date"
                    ),
                ),
                (
                    "Blood_Group",
                    models.CharField(max_length=10, verbose_name="Blood Group"),
                ),
                (
                    "Medical_Health",
                    models.CharField(
                        max_length=5, null=True, verbose_name="Medical Health"
                    ),
                ),
                (
                    "Joining_Date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Joining Date"
                    ),
                ),
                (
                    "Salary_Increment_Date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Salary Increment Date"
                    ),
                ),
                (
                    "Experience",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Experience (years)",
                    ),
                ),
                (
                    "Leave_Date",
                    models.DateField(blank=True, null=True, verbose_name="Leave Date"),
                ),
                (
                    "Leave_Resume",
                    models.DateField(
                        blank=True, null=True, verbose_name="Leave Resume Date"
                    ),
                ),
                (
                    "Driving_Age",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Driving Age (years)",
                    ),
                ),
                (
                    "Previous_Company",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Previous Company",
                    ),
                ),
                (
                    "Tank_Lorry",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Tank Lorry"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Drivers",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "LID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Location ID"
                    ),
                ),
                (
                    "Lname",
                    models.CharField(max_length=255, verbose_name="Location Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="VehicleMaker",
            fields=[
                (
                    "VMid",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Vehicle Maker ID",
                    ),
                ),
                (
                    "VMNAME",
                    models.CharField(max_length=255, verbose_name="Vehicle Maker Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Vehicle Makers",
            },
        ),
        migrations.CreateModel(
            name="VehicleOwner",
            fields=[
                (
                    "VO_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Vehicle Owner ID",
                    ),
                ),
                (
                    "VO_name",
                    models.CharField(max_length=255, verbose_name="Vehicle Owner Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Vehicle Owners",
            },
        ),
        migrations.CreateModel(
            name="Violations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(max_length=1, verbose_name="Violation Type"),
                ),
            ],
            options={
                "verbose_name": "Violation",
                "verbose_name_plural": "Violations",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "VH_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Vehicle ID"
                    ),
                ),
                (
                    "VH_number",
                    models.CharField(max_length=20, verbose_name="Vehicle Number"),
                ),
                (
                    "VH_model",
                    models.CharField(max_length=255, verbose_name="Vehicle Model"),
                ),
                (
                    "VH_Engine_no",
                    models.CharField(max_length=50, verbose_name="Engine Number"),
                ),
                (
                    "VH_Chasis_No",
                    models.CharField(max_length=50, verbose_name="Chassis Number"),
                ),
                (
                    "VH_Capacity",
                    models.PositiveIntegerField(verbose_name="Vehicle Capacity"),
                ),
                (
                    "VH_TAX",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tax Expiry Date"
                    ),
                ),
                (
                    "VH_Fitness",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fitness Expiry Date"
                    ),
                ),
                (
                    "VH_Road_Insurance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Road Insurance Expiry Date"
                    ),
                ),
                (
                    "VH_Explosive_License",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Explosive License Expiry Date",
                    ),
                ),
                (
                    "VH_Owner_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.vehicleowner",
                        verbose_name="Owner Name",
                    ),
                ),
                (
                    "VH_make",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.vehiclemaker",
                        verbose_name="Vehicle Maker",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vehicles",
            },
        ),
        migrations.CreateModel(
            name="User_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        max_length=500, null=True, upload_to="user_images/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Driver_Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_date",
                    models.DateField(null=True, verbose_name="Violation Date"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.driver",
                        verbose_name="Driver",
                    ),
                ),
                (
                    "violation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.violations",
                        verbose_name="Violation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Violation",
                "verbose_name_plural": "Driver Violations",
            },
        ),
        migrations.AddField(
            model_name="driver",
            name="HTV_License_Authority",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.location",
                verbose_name="HTV License Authority",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="Oil_Marketing_Company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.company",
                verbose_name="Oil Marketing Company",
            ),
        ),
        migrations.CreateModel(
            name="annual_training_driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completion_date", models.DateField(verbose_name="Completion Date")),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.annual_training",
                        verbose_name="Training",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "HSE Training Driver",
                "verbose_name_plural": "HSE Training Drivers",
            },
        ),
    ]
