# Generated by Django 5.0.10 on 2025-02-05 10:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualDrill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Drill Name")),
                (
                    "drilling_month",
                    models.CharField(max_length=50, verbose_name="Drill Month"),
                ),
            ],
            options={
                "verbose_name": "Drill Training",
                "verbose_name_plural": "Drill Trainings",
            },
        ),
        migrations.CreateModel(
            name="AnnualTraining",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Training Name"),
                ),
                (
                    "training_month",
                    models.CharField(max_length=50, verbose_name="Training Month"),
                ),
            ],
            options={
                "verbose_name": "HSE Training",
                "verbose_name_plural": "HSE Trainings",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Company ID"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(max_length=10, verbose_name="Abbreviation"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Company Name")),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Location ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Location Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="ToolBoxMeetingTopic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "topic",
                    models.CharField(
                        max_length=255, verbose_name="Tool Box Meeting Topic"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Box Meeting",
                "verbose_name_plural": "Tool Box Meetings",
            },
        ),
        migrations.CreateModel(
            name="VehicleMaker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Vehicle Maker ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Vehicle Maker Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Vehicle Makers",
            },
        ),
        migrations.CreateModel(
            name="VehicleOwner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Vehicle Owner ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Vehicle Owner Name"),
                ),
            ],
            options={
                "verbose_name_plural": "Vehicle Owners",
            },
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "violation_type",
                    models.CharField(max_length=255, verbose_name="Violation Type"),
                ),
            ],
            options={
                "verbose_name": "Violation",
                "verbose_name_plural": "Violations",
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Driver ID"
                    ),
                ),
                (
                    "driver_number",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Driver Number"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="driver_images/",
                        verbose_name="Driver Image",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Driver Name"
                    ),
                ),
                (
                    "father_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Father Name"
                    ),
                ),
                (
                    "cnic",
                    models.CharField(max_length=13, null=True, verbose_name="CNIC"),
                ),
                (
                    "cnic_validity",
                    models.DateField(
                        blank=True, null=True, verbose_name="CNIC Validity Date"
                    ),
                ),
                (
                    "cell_phone_num",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Cell Phone Number"
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "dl_status",
                    models.CharField(
                        choices=[("HTV", "HTV"), ("PSV", "PSV"), ("LTV", "LTV")],
                        max_length=3,
                        null=True,
                        verbose_name="Driving License Status",
                    ),
                ),
                (
                    "motorway_trained",
                    models.CharField(
                        max_length=14, null=True, verbose_name="Motorway Trained"
                    ),
                ),
                (
                    "ddc_issue_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Motorway Certification Issue Date",
                    ),
                ),
                ("address", models.TextField(null=True, verbose_name="Address")),
                (
                    "license_no",
                    models.CharField(
                        max_length=20, null=True, verbose_name="License Number"
                    ),
                ),
                (
                    "htv_license_issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="HTV License Issue Date"
                    ),
                ),
                (
                    "htv_license_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="HTV License Expiry Date"
                    ),
                ),
                (
                    "ddc_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="DDC Expiry Date"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        max_length=16, null=True, verbose_name="Education"
                    ),
                ),
                (
                    "medical_status",
                    models.BooleanField(null=True, verbose_name="Medical Status"),
                ),
                (
                    "medical_report_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Medical Report Date"
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Lab Name"
                    ),
                ),
                (
                    "medical_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Medical Expiry Date"
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(max_length=10, verbose_name="Blood Group"),
                ),
                (
                    "medical_health",
                    models.CharField(
                        max_length=5, null=True, verbose_name="Medical Health"
                    ),
                ),
                (
                    "joining_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Joining Date"
                    ),
                ),
                (
                    "salary_increment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Salary Increment Date"
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Experience (years)",
                    ),
                ),
                (
                    "leave_date",
                    models.DateField(blank=True, null=True, verbose_name="Leave Date"),
                ),
                (
                    "leave_resume_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Leave Resume Date"
                    ),
                ),
                (
                    "driving_age",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Driving Age (years)",
                    ),
                ),
                (
                    "previous_company",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Previous Company",
                    ),
                ),
                (
                    "tank_lorry",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Tank Lorry"
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True, verbose_name="Age")),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.company",
                        verbose_name="Oil Marketing Company",
                    ),
                ),
                (
                    "htv_license_authority",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.location",
                        verbose_name="HTV License Authority",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Drivers",
            },
        ),
        migrations.CreateModel(
            name="AnnualTrainingDriver",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "train1_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN1 Completed Date"
                    ),
                ),
                (
                    "train2_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN2 Completed Date"
                    ),
                ),
                (
                    "train3_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN3 Completed Date"
                    ),
                ),
                (
                    "train4_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN4 Completed Date"
                    ),
                ),
                (
                    "train5_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN5 Completed Date"
                    ),
                ),
                (
                    "train6_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN6 Completed Date"
                    ),
                ),
                (
                    "train7_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN7 Completed Date"
                    ),
                ),
                (
                    "train8_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN8 Completed Date"
                    ),
                ),
                (
                    "train9_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN9 Completed Date"
                    ),
                ),
                (
                    "train10_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN10 Completed Date"
                    ),
                ),
                (
                    "train11_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN11 Completed Date"
                    ),
                ),
                (
                    "train12_completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="TRAIN12 Completed Date"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.driver",
                        verbose_name="Driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "HSE Training Driver",
                "verbose_name_plural": "HSE Training Drivers",
            },
        ),
        migrations.CreateModel(
            name="AnnualDrillDriver",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("train1_completed_date", models.DateField(blank=True, null=True)),
                ("train2_completed_date", models.DateField(blank=True, null=True)),
                ("train3_completed_date", models.DateField(blank=True, null=True)),
                ("train4_completed_date", models.DateField(blank=True, null=True)),
                ("train5_completed_date", models.DateField(blank=True, null=True)),
                ("train6_completed_date", models.DateField(blank=True, null=True)),
                ("train7_completed_date", models.DateField(blank=True, null=True)),
                ("train8_completed_date", models.DateField(blank=True, null=True)),
                ("train9_completed_date", models.DateField(blank=True, null=True)),
                ("train10_completed_date", models.DateField(blank=True, null=True)),
                ("train11_completed_date", models.DateField(blank=True, null=True)),
                ("train12_completed_date", models.DateField(blank=True, null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.driver",
                        verbose_name="Driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drill Driver",
                "verbose_name_plural": "Drill Drivers",
            },
        ),
        migrations.CreateModel(
            name="DriverToolBoxMeetingAttended",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "no_of_times_attended",
                    models.IntegerField(verbose_name="Times Attended"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.driver",
                        verbose_name="Driver",
                    ),
                ),
                (
                    "meeting_topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.toolboxmeetingtopic",
                        verbose_name="Meeting Topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        max_length=500,
                        null=True,
                        upload_to="user_images/",
                        verbose_name="User Image",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tl_number",
                    models.CharField(
                        max_length=255, null=True, verbose_name="TL Number"
                    ),
                ),
                ("capacity", models.IntegerField(null=True, verbose_name="Capacity")),
                (
                    "chambers",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Chambers"
                    ),
                ),
                ("model", models.IntegerField(null=True, verbose_name="Model")),
                (
                    "engine_number",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Engine Number"
                    ),
                ),
                (
                    "chassis_number",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Chassis Number"
                    ),
                ),
                (
                    "status",
                    models.CharField(max_length=255, null=True, verbose_name="Status"),
                ),
                (
                    "vehicle_type",
                    models.CharField(max_length=255, null=True, verbose_name="Type"),
                ),
                (
                    "trailer_id",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Trailer ID"
                    ),
                ),
                (
                    "brand",
                    models.CharField(max_length=255, null=True, verbose_name="Brand"),
                ),
                (
                    "nha_configuration_class",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="NHA Configuration Class",
                    ),
                ),
                (
                    "gross_empty_trailer_weight",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Gross Empty Trailer Weight",
                    ),
                ),
                (
                    "dip_chart_date",
                    models.DateField(null=True, verbose_name="DIP CHART Date"),
                ),
                (
                    "insurance_date",
                    models.DateField(null=True, verbose_name="Insurance Date"),
                ),
                (
                    "tax_paid_date",
                    models.DateField(null=True, verbose_name="Tax Paid Date"),
                ),
                (
                    "fitness_date",
                    models.DateField(null=True, verbose_name="Fitness Date"),
                ),
                ("q_fom_date", models.DateField(null=True, verbose_name="Q FOM Date")),
                (
                    "route_permit_date",
                    models.DateField(null=True, verbose_name="Route Permit Date"),
                ),
                (
                    "omc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.company",
                        verbose_name="Oil Marketing Company",
                    ),
                ),
                (
                    "maker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.vehiclemaker",
                        verbose_name="Maker",
                    ),
                ),
                (
                    "lease_bank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease_bank_vehicles",
                        to="dashboard.vehicleowner",
                        verbose_name="Lease Bank",
                    ),
                ),
                (
                    "lease_company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease_company_vehicles",
                        to="dashboard.vehicleowner",
                        verbose_name="Lease Company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vehicles",
            },
        ),
        migrations.CreateModel(
            name="DriverViolation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "violation_date",
                    models.DateField(null=True, verbose_name="Violation Date"),
                ),
                (
                    "violation_notes",
                    models.TextField(null=True, verbose_name="Violation Notes"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.driver",
                        verbose_name="Driver",
                    ),
                ),
                (
                    "violation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.violation",
                        verbose_name="Violation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Violation",
                "verbose_name_plural": "Driver Violations",
            },
        ),
    ]
