# Generated by Django 4.2.6 on 2023-10-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_remove_annual_training_driver_train10_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annual_training_driver",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
