# Generated by Django 4.2.6 on 2023-10-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_annual_training_driver_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annual_training_driver",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.driver",
                verbose_name="User",
            ),
        ),
    ]
