# Generated by Django 4.2.6 on 2023-10-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_annual_drill_annual_drill_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annual_drill_driver",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.driver",
                verbose_name="User",
            ),
        ),
    ]
