# Generated by Django 4.0.10 on 2023-10-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_annual_drill_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_violation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='violations',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='violations',
            name='violation_type',
            field=models.CharField(max_length=255, verbose_name='Violation Type'),
        ),
        migrations.CreateModel(
            name='tool_box_meeting_topics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_topic', models.CharField(max_length=255, verbose_name='Tool Box Meeting Topic')),
                ('driver_attending', models.ManyToManyField(related_name='meeting_topics_attended', to='dashboard.driver')),
            ],
            options={
                'verbose_name': 'Tool Box Meeting',
                'verbose_name_plural': 'Tool Box Meetings',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='meetings_attended',
            field=models.ManyToManyField(related_name='attendees', to='dashboard.tool_box_meeting_topics'),
        ),
    ]
