# Generated by Django 4.2.6 on 2023-10-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_driver_violation_id_alter_violations_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool_box_meeting_topics',
            name='driver_attending',
        ),
    ]
