# Generated by Django 4.2.6 on 2023-10-27 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_tool_box_meeting_topics_driver_attending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='meetings_attended',
        ),
        migrations.CreateModel(
            name='driver_tool_box_meeting_attended',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_times_meeting_attended', models.IntegerField(max_length=100)),
                ('meeting_attended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.driver')),
                ('meetings_attended', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tool_box_meeting_topics')),
            ],
        ),
    ]
