# Generated by Django 4.2.6 on 2023-10-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_driver_meetings_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_tool_box_meeting_attended',
            name='no_of_times_meeting_attended',
            field=models.IntegerField(),
        ),
    ]
