# Generated by Django 4.2.6 on 2023-10-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_driver_tool_box_meeting_attended_no_of_times_meeting_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_violation',
            name='violation_notes',
            field=models.TextField(null=True),
        ),
    ]
