# Generated by Django 4.2.6 on 2023-10-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_driver_violation_violation_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='DDC_Date',
            new_name='DDC_Expiry_Date',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='Motorway_Cissue_Date',
            new_name='DDC_Issue_Date',
        ),
    ]
