# Generated by Django 4.2.6 on 2023-10-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_ddc_date_driver_ddc_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='CNIC',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
