# Generated by Django 4.2.6 on 2023-10-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_driver_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
