# Generated by Django 4.2.6 on 2023-11-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_driver_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
