# Generated by Django 4.2.6 on 2023-11-05 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_delete_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TL_Number', models.CharField(max_length=255, null=True)),
                ('Capacity', models.IntegerField(null=True)),
                ('Chambers', models.CharField(max_length=255, null=True)),
                ('Model', models.IntegerField(null=True)),
                ('Engine_Number', models.CharField(max_length=255, null=True)),
                ('Chassis_Number', models.CharField(max_length=255, null=True)),
                ('Status', models.CharField(max_length=255, null=True)),
                ('Type', models.CharField(max_length=255, null=True)),
                ('Trailer_ID', models.CharField(max_length=255, null=True)),
                ('Brand', models.CharField(max_length=255, null=True)),
                ('NHA_Configuration_Class', models.CharField(max_length=255, null=True)),
                ('Gross_Empty_Trailer_Weight', models.CharField(max_length=255, null=True)),
                ('DIP_CHART_Date', models.DateField(null=True)),
                ('INSURANCE_Date', models.DateField(null=True)),
                ('TAX_PAID_Date', models.DateField(null=True)),
                ('FITNISSE_Date', models.DateField(null=True)),
                ('Q_FOM_Date', models.DateField(null=True)),
                ('Route_Permit_Date', models.DateField(null=True)),
                ('LEASE_BANK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_Owner_Bank', to='dashboard.vehicleowner')),
                ('LEASE_COMPANY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_Owner_Lease', to='dashboard.vehicleowner')),
                ('Make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.vehiclemaker')),
                ('OMC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company')),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
